# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Test

import flatbuffers

class UploadRows(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUploadRows(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UploadRows()
        x.Init(buf, n + offset)
        return x

    # UploadRows
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UploadRows
    def Rows(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .row_object import row_object
            obj = row_object()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UploadRows
    def RowsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def UploadRowsStart(builder): builder.StartObject(1)
def UploadRowsAddRows(builder, rows): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(rows), 0)
def UploadRowsStartRowsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def UploadRowsEnd(builder): return builder.EndObject()
